PLANS = {
    "free": {
        "task_limit": 10,
        "api_limit": 100,
        "price_cents": 0,
        "display_price": "免费",
        "allowed_ai_providers": ["deepseek"],
        "allowed_ai_models": ["deepseek-chat"],
        "ai_policy_note": "适合先体验基础 AI 选品分析。",
        "supports_custom_model": False,
    },
    "starter": {
        "task_limit": 100,
        "api_limit": 1000,
        "price_cents": 9900,
        "display_price": "¥99 / 月",
        "allowed_ai_providers": ["deepseek", "qwen"],
        "allowed_ai_models": ["deepseek-chat", "qwen-plus"],
        "ai_policy_note": "适合日常选品、分析与轻量决策。",
        "supports_custom_model": False,
    },
    "pro": {
        "task_limit": 1000,
        "api_limit": 10000,
        "price_cents": 29900,
        "display_price": "¥299 / 月",
        "allowed_ai_providers": ["deepseek", "qwen", "kimi", "doubao", "zhipu", "openai"],
        "allowed_ai_models": [
            "deepseek-chat",
            "qwen-plus",
            "moonshot-v1-8k",
            "doubao-1-5-lite-32k-250115",
            "glm-4-flash",
            "gpt-4o-mini",
        ],
        "ai_policy_note": "适合高频分析、更多模型切换与更强稳定性。",
        "supports_custom_model": False,
    },
    "enterprise": {
        "task_limit": -1,
        "api_limit": -1,
        "price_cents": 99900,
        "display_price": "¥999 / 月起",
        "allowed_ai_providers": ["deepseek", "qwen", "kimi", "doubao", "zhipu", "openai"],
        "allowed_ai_models": [
            "deepseek-chat",
            "qwen-plus",
            "moonshot-v1-8k",
            "doubao-1-5-lite-32k-250115",
            "glm-4-flash",
            "gpt-4o-mini",
        ],
        "ai_policy_note": "适合团队协作、全模型访问与后续企业专属接入。",
        "supports_custom_model": True,
    },
}
