export {
  WS_URL,
  analyzeFull,
  analyzeFullPublic,
  analyzeMarketKeyword,
  analyzeProduct,
  analyzeTitle,
  batchDeleteProducts,
  crawlProduct,
  deleteProduct,
  extractPublicProduct,
  getApiBaseUrl,
  getApiRootUrl,
  getApiV1BaseUrl,
  getCurrentUser,
  getDashboardSources,
  getDashboardSummary,
  getDashboardTasks,
  getDashboardTrends,
  getP5Rankings,
  getP5Recommendations,
  getProduct,
  getProducts,
  getProductIntelligence,
  getSystemHealth,
  getTaskStatus,
  getWsBaseUrl,
  isAuthError,
  isNewDashboardEnabled,
  login,
  matchSuppliers,
  predictP5Product,
  recommendBusinessTruth,
  recommendDecision,
} from "@/lib/api";

export const API_DOMAIN_MAP = {
  assetVault: "/api/v1/products",
  signalCapture: "/api/v1/products/crawl",
  insightEngine: "/api/v1/analyze",
  marketRadar: "/api/v1/market",
  supplyNetwork: "/api/v1/suppliers",
  decisionStudio: "/api/v1/decision",
} as const;
